<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<div class="tfa-modal-content-body">
    <p>
        <strong><?= $block->escapeHtml(__('All currently active providers will not be available')) ?></strong>
        <?= $block->escapeHtml(
            __('which means all admin users will be required to configure an available method before they can login.')
        ) ?>
    </p>
</div>
