<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\TwoFactorAuth\Block\Configure $block */

$list = $block->getProvidersList();
?>
<p id="2fa-configure-header">
    <?= $block->escapeHtml(__(
        'Please select one or more Two-Factor Authorization providers to be used to authorize admin users'
    )); ?>
</p>
<div id="2fa-providers-list">
    <?php if (!$list): ?>
        <p class="mage-error">
            <?= $block->escapeHtml(__(
                'No providers are available to select, please '
                . 'configure required 2FA provider settings on the server via CLI'
            )); ?>
        </p>
    <?php else: ?>
        <form class="tfa-configure-providers" method="post"
              action="<?= $block->escapeHtmlAttr($block->getActionUrl()) ?>">
            <ul class="tfa-provider_list">
                <?php foreach ($list as $providerData): ?>
                    <li class="tfa-provider">
                        <input type="checkbox"
                               name="tfa_selected[<?= $block->escapeHtmlAttr($providerData['code']) ?>]"
                               class="tfa-checkbox"
                               id="2fa_checkbox-<?= $block->escapeHtmlAttr($providerData['code']) ?>"/>
                        <label for="2fa_checkbox-<?= $block->escapeHtmlAttr($providerData['code']) ?>">
                            <img src="<?= $block->escapeHtmlAttr($providerData['icon']) ?>"/>
                            <span><?= $block->escapeHtml($providerData['name']) ?></span>
                        </label>
                    </li>
                <?php endforeach; ?>
            </ul>
            <br/>
            <?= $block->getBlockHtml('formkey') ?>
            <input type="submit" value="<?= $block->escapeHtmlAttr(__('Apply')); ?>" class="action-primary" />
        </form>
    <?php endif; ?>
</div>
