<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Backend\Block\Template $block */
?>
<div>
    <p><?= $block->escapeHtml(__(
        'You need to configure Two-Factor Authorization in order to proceed to your store\'s admin area'
    )); ?></p>
    <p><?= $block->escapeHtml(__(
        'An E-mail was sent to you with further instructions'
    )); ?></p>
</div>
