<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div id="tfa-auth-container" data-bind="scope:'tfa-auth'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<?= $block->getChildHtml('change-provider') ?>

<script type="text/x-magento-init">
{
    "#tfa-auth-container": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>
