<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block Magento\ReCaptchaAdminUi\Block\ReCaptcha */
$class = $block->getSize() === 'invisible' ? 'field-invisible-recaptcha' : 'field-recaptcha';
?>
<?php if ($block->canDisplayCaptcha()) : ?>
<div class="admin__field <?= /* @noEscape */ $class ?>">
    <div id="admin-recaptcha"></div>
</div>

<script type="text/javascript">
    require([
        'jquery'
    ], function (
        $
    ) {
        const element = document.createElement('script');
        const scriptTag = document.getElementsByTagName('script')[0];

        element.async = true;
        element.src = 'https://www.google.com/recaptcha/api.js'
            + '?onload=globalOnRecaptchaOnLoadCallback&render=explicit';

        window.globalOnRecaptchaOnLoadCallback = function () {
            let token = '';

            this.widgetId = grecaptcha.render('admin-recaptcha', {
                'sitekey': '<?= $block->escapeJs($block->getPublicKey()) ?>',
                'size': '<?= $block->escapeJs($block->getSize()) ?>',
                'badge': 'inline',
                'callback': function (token) { // jscs:ignore jsDoc
                    <?php if ($block->getSize() === 'invisible') : ?>
                    this.token = token;
                    $('#login-form').submit();
                    <?php endif; ?>
                }.bind(this)
            });

            <?php if ($block->getSize() === 'invisible') : ?>
            $('#login-form').submit(function (event) {
                if (!this.token) {
                    event.preventDefault(event);
                    event.stopImmediatePropagation();
                    grecaptcha.execute(this.widgetId);
                }
            }.bind(this));
            <?php endif; ?>
        }.bind(this);

        scriptTag.parentNode.insertBefore(element, scriptTag);
    });
</script>
<?php endif; ?>
