<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block Magento\ReCaptchaUi\Block\ReCaptcha */
$config = $block->getCaptchaUiConfig();
$renderingOptions = $config['rendering'] ?? [];
$isInvisible = !empty($config['invisible']);
?>
<div class="admin__field <?= /* @noEscape */ $isInvisible ? 'field-invisible-recaptcha' : 'field-recaptcha' ?>">
    <div id="admin-recaptcha"
         class="admin-recaptcha-content<?=
         /* @noEscape */ !empty($renderingOptions['size']) ? ' size-' . $renderingOptions['size'] : '' ?>"></div>
</div>

<script>
    require([
        'jquery'
    ], function (
        $
    ) {
        const element = document.createElement('script');
        const scriptTag = document.getElementsByTagName('script')[0];

        element.async = true;
        element.src = 'https://www.google.com/recaptcha/api.js'
            + '?onload=globalOnRecaptchaOnLoadCallback&render=explicit';

        window.globalOnRecaptchaOnLoadCallback = function () {
            let token = '';

            this.widgetId = grecaptcha.render('admin-recaptcha', {
                <?php foreach ($renderingOptions as $key => $value): ?>
                '<?= $block->escapeJs($key) ?>': '<?= $block->escapeJs($value) ?>',
                <?php endforeach; ?>
                'callback': function (token) { // jscs:ignore jsDoc
                    <?php if ($isInvisible): ?>
                    this.token = token;
                    $('#login-form').submit();
                    <?php endif; ?>
                }.bind(this)
            });

            <?php if ($isInvisible): ?>
            $('#login-form').submit(function (event) {
                if (!this.token) {
                    event.preventDefault(event);
                    event.stopImmediatePropagation();
                    grecaptcha.execute(this.widgetId);
                }
            }.bind(this));
            <?php endif; ?>
        }.bind(this);

        scriptTag.parentNode.insertBefore(element, scriptTag);
    });
</script>
